#!/usr/bin/env python3

import openrazer.client

razer = openrazer.client.DeviceManager()
razer.turn_off_on_screensaver = False

for device in razer.devices:
    device.brightness = 100
    device.fx.static(255, 255, 255)
