"Splits
set splitright
set splitbelow

"Search
set incsearch
set hlsearch
set ignorecase
nnoremap qq :nohl<CR>

"Wildmenu
set wildmenu

"Ignore some extensions
set wildignore+=*.so,*.o,*.swp

"Remap escape
imap jj <Esc>

"Syntax processing
syntax on

"Invisibles
set listchars=tab:..,trail:~
set list

"Remap page moves
map <C-J> <S-Down>
map <C-K> <S-Up>

"Buffers integration
set hidden
set history=500
nnoremap <C-H> :bprev<CR>
nnoremap <C-L> :bnext<CR>

"Identation
filetype plugin indent on
syntax enable
set nosmartindent
set cindent
set softtabstop=2
set shiftwidth=2
set expandtab

"But still insert tab
inoremap hh <C-V><Tab>

"Just in case I can not find
"these on the keyboard
inoremap ww <
inoremap WW >

"Show matching chars
set showmatch

"Splits
cabbrev s split
cabbrev v vsplit

"Status line
set laststatus=2
set noshowmode

"Line numbers
set number
set relativenumber

"Do not show command
set noshowcmd

"Quickfix colors
hi QuickFixLine cterm=None ctermbg=None ctermfg=None
