-- I would like to put these alphabetically, but the order matters...

require('utils')
require('colors')
require('options')
require('lsp')

require('plugins')
require('_base16')
require('_compe')
require('_dashboard')
require('_galaxyline')
require('_gitsigns')
require('_indent-blankline')
require('_lspconfig')
require('_lspkind')
require('_nvim-autopairs')
require('_nvim-reload')
require('_nvim-tree')
require('_nvim-web-devicons')
require('_telescope')
require('_trouble')
require('_which-key')

require('highlights')
