#! /usr/bin/env sh

# BAR

yabai -m config status_bar                   off


# GLOBAL

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                float
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xffe77e74
yabai -m config insert_window_border_color   0xffe77e74
yabai -m config normal_window_border_color   0xff505050
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move


# SPACES

yabai -m config layout                       bsp
yabai -m config --space 8  layout            float
yabai -m config --space 9  layout            float
yabai -m config --space 10 layout            float
yabai -m config top_padding                  10
yabai -m config bottom_padding               10
yabai -m config left_padding                 10
yabai -m config right_padding                10
yabai -m config window_gap                   10


# IGNORES

yabai -m rule --add app="^Préférences Système$" manage=off
yabai -m rule --add app="^Fantastical" manage=off
yabai -m rule --add app="^Dashlane$" manage=off
yabai -m rule --add app="^Calculette$" manage=off


echo "The yabai configuration has loaded!"
