local wk = require('which-key')

wk.setup({
  icons = {
    mappings = false,
    breadcrumb = '»',
    separator = '→ ',
    group = '+',
  },
  layout = {
    height = { min = 1, max = 10 },
    spacing = 3,
    align = 'left',
  },
  show_help = false,
})

wk.add({
  { "<leader><leader>", "<cmd>Telescope buffers prompt_title= previewer=false<cr>", desc = "Buffers" },
  { "<leader>E", "<cmd>NvimTreeFindFile<cr>", desc = "File Tree (Current)" },
  { "<leader>S", "<cmd>HopChar1<cr>", desc = "Jump To (1)" },
  { "<leader>d", group = "document" },
  { "<leader>dS", "<cmd>wa<cr>", desc = "Save All Changes" },
  { "<leader>dr", "<cmd>u0<cr>", desc = "Restore Changes" },
  { "<leader>ds", "<cmd>w<cr>", desc = "Save Changes" },
  { "<leader>e", "<cmd>NvimTreeToggle<cr>", desc = "File Tree" },
  { "<leader>f", group = "find" },
  { "<leader>fF", "<cmd>Telescope git_files prompt_title= previewer=false<cr>", desc = "File (Git)" },
  { "<leader>fb", "<cmd>Telescope buffers prompt_title= previewer=false<cr>", desc = "Buffer" },
  { "<leader>fc", "<cmd>Telescope command_history prompt_title= previewer=false<cr>", desc = "Command (History)" },
  { "<leader>ff", "<cmd>Telescope find_files prompt_title= previewer=false<cr>", desc = "File (All)" },
  { "<leader>fg", "<cmd>Telescope live_grep prompt_title= previewer=false<cr>", desc = "Find Text" },
  { "<leader>fj", "<cmd>Telescope jumplist prompt_title= previewer=false<cr>", desc = "Jumplist" },
  { "<leader>fk", "<cmd>Telescope keymaps prompt_title= previewer=false<cr>", desc = "Keymaps" },
  { "<leader>fo", "<cmd>Telescope vim_options prompt_title= previewer=false<cr>", desc = "Vim Option" },
  { "<leader>fp", "<cmd>Telescope oldfiles prompt_title= previewer=false<cr>", desc = "Previously Opened" },
  { "<leader>fr", "<cmd>Telescope registers prompt_title= previewer=false<cr>", desc = "Registers" },
  { "<leader>m", group = "misc" },
  { "<leader>mh", "<cmd>echo map(synstack(line('.'), col('.')), 'synIDattr(v:val, \"name\")')<cr>", desc = "Show Highlight Group" },
  { "<leader>ms", "<cmd>source %<cr>", desc = "Source Current" },
  { "<leader>n", "<cmd>nohl<cr>", desc = "No Highlight" },
  { "<leader>p", group = "packer" },
  { "<leader>ps", "<cmd>PackerSync<cr>", desc = "Packer Sync" },
  { "<leader>pu", "<cmd>PackerUpdate<cr>", desc = "Packer Update" },
  { "<leader>q", group = "windows/buffers" },
  { "<leader>qH", "<C-w>H", desc = "Move Window Left" },
  { "<leader>qJ", "<C-w>J", desc = "Move Window Down" },
  { "<leader>qK", "<C-w>K", desc = "Move Window Right" },
  { "<leader>qL", "<C-w>L", desc = "Move Window Up" },
  { "<leader>qc", "<cmd>close<cr>", desc = "Close" },
  { "<leader>qd", "<cmd>bdelete<cr>", desc = "Delete Buffer" },
  { "<leader>qh", "<C-w>h", desc = "Go Window Left" },
  { "<leader>qi", "<C-i>", desc = "Jump Forward" },
  { "<leader>qj", "<C-w>j", desc = "Go Window Down" },
  { "<leader>qk", "<C-w>k", desc = "Go Window Right" },
  { "<leader>ql", "<C-w>l", desc = "Go Window Up" },
  { "<leader>qn", "<cmd>bnext<cr>", desc = "Next Buffer" },
  { "<leader>qo", "<C-o>", desc = "Jump Backward" },
  { "<leader>qp", "<cmd>bprev<cr>", desc = "Previous Buffer" },
  { "<leader>qq", "<cmd>quit<cr>", desc = "Quit" },
  { "<leader>qs", "<cmd>split<cr>", desc = "Split Horizontally" },
  { "<leader>qv", "<cmd>vsplit<cr>", desc = "Split Vertically" },
  { "<leader>s", "<cmd>HopChar2<cr>", desc = "Jump To (2)" },
  { "<leader>w", "/", desc = "Search" },
})
