# PREZTO
source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"

# DO NOT UNDERLINE PATHS
ZSH_HIGHLIGHT_STYLES[path]=''

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
source ~/.fzfcolors.zsh

bindkey '^H' fzf-file-widget
bindkey '^J' fzf-cd-widget
bindkey '^K' fzf-history-widget

FZF_ALT_C_COMMAND="fd -t d -E Library -E Applications"
FZF_CTRL_T_COMMAND="fd -t f -E Library -E Applications"

# ALIASES
source ~/.aliases.zsh

# FUNCTIONS
source ~/.fn.zsh

# NO CORRECTION
unsetopt correct

# CTRL+N/P IN INSERT MODE
bindkey '^P' up-history
bindkey '^N' down-history

# Starship
eval "$(starship init zsh)"
