# Environment
source ~/.dotfiles/bash/environment.sh

# Aliases
source ~/.dotfiles/bash/aliases.sh

# Bash options
source ~/.dotfiles/bash/options.sh

# Get colors
source ~/.dotfiles/bash/colors.sh
getColors

# Get the prompt
source ~/.dotfiles/bash/prompt.sh

# Man colors
source ~/.dotfiles/bash/man.sh

# Blih functions
source ~/.dotfiles/bash/blih.sh
